import type { DiscoveredCompany, LeadDiscoveryProvider, LeadFinderCriteria } from "@/lib/discovery/types";

// All company names below are invented and do not represent real
// organizations. Contact emails use the IANA-reserved ".example" TLD,
// which is guaranteed to never resolve or accept mail — an extra technical
// safeguard on top of the isDemo send-guard (spec section 46).
type DemoCompanyTemplate = Omit<DiscoveredCompany, "source" | "isDemo">;

const DEMO_POOL: DemoCompanyTemplate[] = [
  {
    name: "Marrow Studio",
    website: null,
    industry: "Fashion",
    country: "Germany",
    city: "Berlin",
    sizeMin: 80,
    sizeMax: 150,
    description:
      "Contemporary fashion label. Recently launched a new collection line and has been rebranding its visual identity across retail and digital.",
    contactName: "Jana Voss",
    contactRole: "Head of Brand",
    contactEmail: "jana.voss@marrowstudio.example",
    linkedinUrl: "https://linkedin.com/company/marrowstudio-example",
  },
  {
    name: "Halvorsen & Kade",
    website: null,
    industry: "Fashion",
    country: "Germany",
    city: "Munich",
    sizeMin: 200,
    sizeMax: 400,
    description:
      "Premium apparel group running a seasonal campaign across social channels ahead of a new product launch.",
    contactName: "Lukas Reimann",
    contactRole: "Marketing Director",
    contactEmail: "lukas.reimann@halvorsenkade.example",
    linkedinUrl: "https://linkedin.com/company/halvorsenkade-example",
  },
  {
    name: "Kettlework Foods",
    website: null,
    industry: "Food",
    country: "Germany",
    city: "Hamburg",
    sizeMin: 150,
    sizeMax: 300,
    description:
      "Premium food producer launching a new product line this year with an accompanying marketing campaign.",
    contactName: "Elena Brandt",
    contactRole: "Head of Marketing",
    contactEmail: "elena.brandt@kettleworkfoods.example",
    linkedinUrl: "https://linkedin.com/company/kettleworkfoods-example",
  },
  {
    name: "Foundry & Oak",
    website: null,
    industry: "Food",
    country: "Austria",
    city: "Vienna",
    sizeMin: 60,
    sizeMax: 120,
    description: "Restaurant and hospitality group expanding with new locations and a rebranding effort.",
    contactName: "Paul Aigner",
    contactRole: "Founder",
    contactEmail: "paul.aigner@foundryoak.example",
    linkedinUrl: "https://linkedin.com/company/foundryoak-example",
  },
  {
    name: "Nimbus Technologies",
    website: null,
    industry: "Technology",
    country: "Germany",
    city: "Berlin",
    sizeMin: 300,
    sizeMax: 800,
    description:
      "B2B SaaS company that recently closed a funding round and is now investing in a brand campaign and new product launch content.",
    contactName: "Sophie Lindgren",
    contactRole: "VP Marketing",
    contactEmail: "sophie.lindgren@nimbustech.example",
    linkedinUrl: "https://linkedin.com/company/nimbustech-example",
  },
  {
    name: "Vantage Cloud Systems",
    website: null,
    industry: "Technology",
    country: "Netherlands",
    city: "Amsterdam",
    sizeMin: 500,
    sizeMax: 1200,
    description: "Enterprise software vendor running a rebranding and new product launch campaign this quarter.",
    contactName: "Tomas de Wit",
    contactRole: "Director of Communications",
    contactEmail: "tomas.dewit@vantagecloud.example",
    linkedinUrl: "https://linkedin.com/company/vantagecloud-example",
  },
  {
    name: "Kastl Motors",
    website: null,
    industry: "Automotive",
    country: "Germany",
    city: "Stuttgart",
    sizeMin: 800,
    sizeMax: 2000,
    description: "Automotive supplier launching a new product line and expanding into new markets this year.",
    contactName: "Markus Feldmann",
    contactRole: "Head of Brand & Communications",
    contactEmail: "markus.feldmann@kastlmotors.example",
    linkedinUrl: "https://linkedin.com/company/kastlmotors-example",
  },
  {
    name: "Reither Mobility Group",
    website: null,
    industry: "Automotive",
    country: "Austria",
    city: "Graz",
    sizeMin: 400,
    sizeMax: 900,
    description: "Mobility company running a major rebranding campaign across its product portfolio.",
    contactName: "Nina Gruber",
    contactRole: "Marketing Lead",
    contactEmail: "nina.gruber@reithermobility.example",
    linkedinUrl: "https://linkedin.com/company/reithermobility-example",
  },
  {
    name: "Veloura Beauty",
    website: null,
    industry: "Beauty",
    country: "Germany",
    city: "Dusseldorf",
    sizeMin: 100,
    sizeMax: 250,
    description: "Beauty brand launching a new product collection with heavy social media campaign activity.",
    contactName: "Carla Mertens",
    contactRole: "Head of Brand",
    contactEmail: "carla.mertens@velourabeauty.example",
    linkedinUrl: "https://linkedin.com/company/velourabeauty-example",
  },
  {
    name: "Solene Skincare",
    website: null,
    industry: "Beauty",
    country: "Switzerland",
    city: "Zurich",
    sizeMin: 60,
    sizeMax: 130,
    description: "Skincare company expanding into new markets with a rebranding and content campaign.",
    contactName: "Anouk Baumann",
    contactRole: "Founder & CEO",
    contactEmail: "anouk.baumann@soleneskincare.example",
    linkedinUrl: "https://linkedin.com/company/soleneskincare-example",
  },
  {
    name: "Trailhead Sports",
    website: null,
    industry: "Sports",
    country: "Germany",
    city: "Cologne",
    sizeMin: 200,
    sizeMax: 500,
    description: "Sportswear brand launching a new product line ahead of the season with a national campaign.",
    contactName: "Felix Ortmann",
    contactRole: "Head of Marketing",
    contactEmail: "felix.ortmann@trailheadsports.example",
    linkedinUrl: "https://linkedin.com/company/trailheadsports-example",
  },
  {
    name: "Summit Athletics Group",
    website: null,
    industry: "Sports",
    country: "United Kingdom",
    city: "Manchester",
    sizeMin: 300,
    sizeMax: 700,
    description: "Athletics brand running a recruiting campaign and a new product launch simultaneously.",
    contactName: "Olivia Marsh",
    contactRole: "Brand Director",
    contactEmail: "olivia.marsh@summitathletics.example",
    linkedinUrl: "https://linkedin.com/company/summitathletics-example",
  },
  {
    name: "Loop Commerce",
    website: null,
    industry: "E-Commerce",
    country: "Germany",
    city: "Berlin",
    sizeMin: 150,
    sizeMax: 400,
    description: "Fast-growing e-commerce platform running a rebranding and content campaign across channels.",
    contactName: "Julia Falk",
    contactRole: "Head of Growth Marketing",
    contactEmail: "julia.falk@loopcommerce.example",
    linkedinUrl: "https://linkedin.com/company/loopcommerce-example",
  },
  {
    name: "Northgate Retail Group",
    website: null,
    industry: "E-Commerce",
    country: "Netherlands",
    city: "Rotterdam",
    sizeMin: 250,
    sizeMax: 600,
    description: "Direct-to-consumer retail group launching a new product line with a large campaign budget.",
    contactName: "Bram Verhoeven",
    contactRole: "CMO",
    contactEmail: "bram.verhoeven@northgateretail.example",
    linkedinUrl: "https://linkedin.com/company/northgateretail-example",
  },
  {
    name: "Aurelia Hospitality Group",
    website: null,
    industry: "Hospitality",
    country: "Germany",
    city: "Munich",
    sizeMin: 300,
    sizeMax: 700,
    description: "Hotel group opening a new flagship location and launching a rebranding campaign.",
    contactName: "Isabel Krauss",
    contactRole: "Director of Marketing",
    contactEmail: "isabel.krauss@aureliahospitality.example",
    linkedinUrl: "https://linkedin.com/company/aureliahospitality-example",
  },
  {
    name: "Havenwell Resorts",
    website: null,
    industry: "Hospitality",
    country: "Switzerland",
    city: "Geneva",
    sizeMin: 200,
    sizeMax: 450,
    description: "Resort group expanding with a new location and launching a seasonal campaign.",
    contactName: "Claire Dubois",
    contactRole: "Head of Communications",
    contactEmail: "claire.dubois@havenwellresorts.example",
    linkedinUrl: "https://linkedin.com/company/havenwellresorts-example",
  },
  {
    name: "Solene Real Estate",
    website: null,
    industry: "Real Estate",
    country: "Germany",
    city: "Frankfurt",
    sizeMin: 100,
    sizeMax: 250,
    description: "Real estate developer launching a new flagship project with a dedicated brand campaign.",
    contactName: "Daniel Wehner",
    contactRole: "Head of Brand",
    contactEmail: "daniel.wehner@solenerealestate.example",
    linkedinUrl: "https://linkedin.com/company/solenerealestate-example",
  },
  {
    name: "Meridian Property Group",
    website: null,
    industry: "Real Estate",
    country: "United Kingdom",
    city: "London",
    sizeMin: 300,
    sizeMax: 800,
    description: "Property group rebranding ahead of a major new development launch.",
    contactName: "Charlotte Hale",
    contactRole: "Marketing Director",
    contactEmail: "charlotte.hale@meridianproperty.example",
    linkedinUrl: "https://linkedin.com/company/meridianproperty-example",
  },
  {
    name: "Nordform Studio",
    website: null,
    industry: "Architecture",
    country: "Germany",
    city: "Hamburg",
    sizeMin: 60,
    sizeMax: 140,
    description: "Architecture studio launching a new portfolio campaign to showcase recent flagship projects.",
    contactName: "Theo Lindner",
    contactRole: "Partner",
    contactEmail: "theo.lindner@nordformstudio.example",
    linkedinUrl: "https://linkedin.com/company/nordformstudio-example",
  },
  {
    name: "Bregner Architecture Group",
    website: null,
    industry: "Architecture",
    country: "Austria",
    city: "Salzburg",
    sizeMin: 80,
    sizeMax: 180,
    description: "Architecture firm expanding into new markets with a rebranding and content campaign.",
    contactName: "Anna Steinbach",
    contactRole: "Head of Marketing",
    contactEmail: "anna.steinbach@bregnerarchitecture.example",
    linkedinUrl: "https://linkedin.com/company/bregnerarchitecture-example",
  },
  {
    name: "Ferrum Industry Group",
    website: null,
    industry: "Industry",
    country: "Germany",
    city: "Essen",
    sizeMin: 500,
    sizeMax: 1500,
    description: "Industrial manufacturing group launching a recruiting campaign and new product line.",
    contactName: "Stefan Winkler",
    contactRole: "Head of Corporate Communications",
    contactEmail: "stefan.winkler@ferrumindustry.example",
    linkedinUrl: "https://linkedin.com/company/ferrumindustry-example",
  },
  {
    name: "Kessler Industrial Systems",
    website: null,
    industry: "Industry",
    country: "Switzerland",
    city: "Basel",
    sizeMin: 400,
    sizeMax: 1000,
    description: "Industrial systems provider expanding into new markets with a fresh brand campaign.",
    contactName: "Marco Huber",
    contactRole: "Marketing Manager",
    contactEmail: "marco.huber@kesslerindustrial.example",
    linkedinUrl: "https://linkedin.com/company/kesslerindustrial-example",
  },
  {
    name: "Alder & Finch Living",
    website: null,
    industry: "Lifestyle",
    country: "Germany",
    city: "Leipzig",
    sizeMin: 90,
    sizeMax: 200,
    description: "Lifestyle brand launching a new product line and rebranding across social media.",
    contactName: "Mara Sievers",
    contactRole: "Brand Manager",
    contactEmail: "mara.sievers@alderfinch.example",
    linkedinUrl: "https://linkedin.com/company/alderfinch-example",
  },
  {
    name: "Birchwood Living Co.",
    website: null,
    industry: "Lifestyle",
    country: "United Kingdom",
    city: "Bristol",
    sizeMin: 70,
    sizeMax: 160,
    description: "Home & lifestyle brand running a content campaign ahead of a seasonal product launch.",
    contactName: "James Whitfield",
    contactRole: "Head of Brand",
    contactEmail: "james.whitfield@birchwoodliving.example",
    linkedinUrl: "https://linkedin.com/company/birchwoodliving-example",
  },
];

export const demoDiscoveryProvider: LeadDiscoveryProvider = {
  name: "demo",
  async discover(criteria: LeadFinderCriteria): Promise<DiscoveredCompany[]> {
    let pool = DEMO_POOL;

    if (criteria.countries.length > 0) {
      pool = pool.filter((c) => c.country && criteria.countries.includes(c.country));
    }
    if (criteria.industries.length > 0) {
      pool = pool.filter((c) => c.industry && criteria.industries.includes(c.industry));
    }
    pool = pool.filter((c) => (c.sizeMax ?? 0) >= criteria.companySizeMin && (c.sizeMin ?? 0) <= criteria.companySizeMax);

    // Fall back to the full pool if filters were too narrow — a demo
    // provider should always be able to show the workflow end-to-end.
    if (pool.length === 0) pool = DEMO_POOL;

    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    const selected = shuffled.slice(0, Math.max(1, Math.min(criteria.leadCount, shuffled.length)));

    return selected.map((c) => ({ ...c, source: "demo_discovery", isDemo: true }));
  },
};
